spring.application.name=libraryApp

spring.datasource.url=jdbc:mysql://localhost:3306/library
spring.datasource.username=libraryApp
spring.datasource.password=libraryAppTest!

spring.jpa.properties.hibernate.hbm2ddl.auto=none

spring.jpa.properties.hibernate.type.json_format_mapper=mentoring.acomi.library.infrastructure.persistence.configuration.Jackson3HibernateJsonFormatMapper
